CREATE USER project_1_app
WITH PASSWORD 'project_1';

GRANT ALL privileges
ON DATABASE postgres
TO project_1_app;


CREATE TABLE ERS_REIMBURSEMENT_STATUSES(

	REIMB_STATUS_ID	SERIAL,				--PK
	REIMB_STATUS	VARCHAR(10)	UNIQUE,
	
	CONSTRAINT REIMB_STATUS_ID_PK
	PRIMARY KEY (REIMB_STATUS_ID)
);


CREATE TABLE ERS_REIMBURSEMENT_TYPES(

	REIMB_TYPE_ID	SERIAL,				--PK
	REIMB_TYPE		VARCHAR(10) UNIQUE,
	
	CONSTRAINT REIMB_TYPE_ID_PK
	PRIMARY KEY (REIMB_TYPE_ID) 		
);


CREATE TABLE ERS_USER_ROLES(
	
	ROLE_ID			SERIAL,				--PK
	ROLE_NAME		VARCHAR(10)	UNIQUE,
	
	CONSTRAINT ROLE_ID_PK
	PRIMARY KEY (ROLE_ID)
);


CREATE TABLE ERS_USERS(
	
	ERS_USER_ID 	SERIAL, 			 --PK
	USERNAME 		VARCHAR(25)  UNIQUE,
	PASSWORD 		VARCHAR(256),
	FIRST_NAME 		VARCHAR(25),
	LAST_NAME 		VARCHAR(25),
	EMAIL 			VARCHAR(256) UNIQUE,
	USER_ROLE_ID 	INT,				 --FK
	
		CONSTRAINT ERS_USER_ID_PK
	PRIMARY KEY (ERS_USER_ID),
	
		CONSTRAINT USER_ROLE_ID_FK
	FOREIGN KEY (USER_ROLE_ID)
	REFERENCES ERS_USER_ROLES	
);


CREATE TABLE ERS_REIMBURSMENTS(

	REIMB_ID 		SERIAL,				 --PK
	AMOUNT 			NUMERIC(6, 2),
	SUBMITTED 		TIMESTAMP,
	RESOLVED 		TIMESTAMP,
	DESCRIPTION 	TEXT,
	RECEIPT			BYTEA,
	AUTHOR_ID 		INT,				 --FK
	RESOLVER_ID 	INT,				 --FK
	REIMB_STATUS_ID INT,				 --FK
	REIMB_TYPE_ID 	INT,				 --FK
	
		CONSTRAINT REIMB_ID_PK
	PRIMARY KEY (REIMB_ID),
	
		CONSTRAINT AUTHOR_ID_FK
	FOREIGN KEY (AUTHOR_ID)
	REFERENCES ERS_USERS,
	
		CONSTRAINT RESOLVER_ID_FK
	FOREIGN KEY (RESOLVER_ID)
	REFERENCES ERS_USERS,
	
		CONSTRAINT REIMB_STATUS_ID_FK
	FOREIGN KEY (REIMB_STATUS_ID)
	REFERENCES ERS_REIMBURSEMENT_STATUSES,
	
		CONSTRAINT REIMB_TYPE_ID_FK
	FOREIGN KEY (REIMB_TYPE_ID)
	REFERENCES ERS_REIMBURSEMENT_TYPES
);
